default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["USER"] %>  

development:
  <<: *default
  database: development_combine

production:
  <<: *default
  database: production_combine
