default: &default
  adapter: postgresql
  encoding: unicode
  username: mihail 

development:
  <<: *default
  database: development_combine

production:
  <<: *default
  database: production_combine
